### ISSUE TITLE
Possible integration into 30-seconds organization

### ISSUE THREAD

**Issue by Chalarangelo** [30-seconds/30-seconds-of-php-code#61]
Hello, everyone! Our [GitHub organization](https://github.com/30-seconds) would love to have you as part of the team. You will, of course, retain all rights to your code and repository, write access and all the good stuff. The only thing that changes is that the 30-seconds team will be able to help more often with your project's needs and you will get to have access to all our communication channels. 

If you are interested, please reply with the following:
- Main person(s) responsible for the repository after the transfer (i.e. team leaders, up to 3 people).
- Any other people who should be part of the organization as members of the `PHP` team.

If you have any questions and/or concerns, please feel free to ask me about them.

**Comment by peter279k** [comment]
Hi @Chalarangelo, thank you for your reply. It sounds good.

And I think you can ask @sohelamin about this transfer work directly because he is the main owner of this repository.

**Comment by Chalarangelo** [comment]
@sohelamin Your thoughts on this particular matter?

**Comment by sohelamin** [comment]
@Chalarangelo Thanks for the offer.
I will let you know very soon :)

**Comment by sohelamin** [comment]
Hi @Chalarangelo, you can proceed with the further steps for the transfer.

And I think you can add me(@sohelamin) as the main person of this repo and @peter279k as a member of your team.

**Comment by Chalarangelo** [comment]
Ok, here's the rundown of what's about to happen:

- I will invite you both to the @30-seconds organization and create a PHP team.
- After you accept your invitation (@sohelamin) you will be able to transfer the repository to the @30-seconds organization via the repository's settings (if you are asked for a team, pick the PHP team).
- After that point, the repository will be part of the organization and I will add it to the team with appropriate rights.
- @sohelamin, you will also gain access to the **meta** team, which is responsible for a few things such as general directions and systems concerning the repositories.

**Comment by Chalarangelo** [comment]
Welcome to the organization! 😃

**Comment by sohelamin** [comment]
Thank you :)
