### ISSUE TITLE
Update Note message in README

### ISSUE THREAD

**Issue by peter279k** [30-seconds/30-seconds-of-php-code#62]
As title, some messages I think we need to be changed since this repository is the part of `30-seconds` organization.

The messages are as follows:

```
Note: This project is inspired by 30 Seconds of Code, but there is no affiliation with that project.
```

This message I think should be removed/changed.

@sohelamin, what do you think about changing this description?

**Comment by Chalarangelo** [comment]
I suppose that we can just remove the note. I opened #63 for this.

**Comment by peter279k** [comment]
Hi @Chalarangelo, I think it's fined to remove `note` message because it's part of the `30-seconds` now.

**Comment by sohelamin** [comment]
Yeah, that was an unnecessary note.
