### ISSUE TITLE
[NOTICE/DISCUSSION] Migration to new infrastructure

### ISSUE THREAD

**Issue by Chalarangelo** [30-seconds/30-seconds-of-php-code#65]
Hey there, @30-seconds/php team! How's it going? 

As you might have noticed, we are migrating repositories toa new, unified structure and template to make it easier for the core teams to maintain them. I will outline below the list of changes we are thinking of making and you can pitch in and help us (me and @fejes713) figure out the best fit and timeline for this all:

- [ ] Update logo to match the style of the other repositories (@Chalarangelo)
- [ ] Update snippets to the new format and match quality standards (open)
- [ ] Remove leftover scripts, code, systems etc [1] (@fejes713)
- [ ] Copy systems, scripts, tools from [30-seconds/30-seconds-starter](https://github.com/30-seconds/30-seconds-starter) and configure accordingly (@fejes713)
- [ ] Update static parts, guidelines, issue/PR templates (@fejes713)
- [ ] Add Google Analytics, DNS records for php.30secondsofcode.org (@Chalarangelo)
- [ ] Rename to 30-seconds-of-php (all existing links are handled automagically by GitHub to point to the new name) (@Chalarangelo)
- [ ] Set up Travis CI and Netlify (@Chalarangelo)

### Notes

- [1]: If you want, you can keep parts of the existing infrastructure (e.g. a testing system or something similar), as long as you maintain them and keep them up to date and provide us with guidelines and/or help during the migration process on how to integrate them to the new template.

---

Nothing is set in stone yet, but we are trying to get all repositories set up with the new template (check the 30-seconds-of-code and 30-seconds-of-python repositories to see what this looks like) and build it all up as soon as possible. However, we are asking each team to make sure there are as few issues with this as possible, so I'd love to get some feedback from you, guys. If you don't have time to participate in this procedure (which is absolutely fine), I and @fejes713 will take care of pretty much everything, so no worries, just respond below so that we know.

**Comment by sohelamin** [comment]
Sorry guys, I'm on a vacation that's why I couldn't reply and contribute.
Hope I'll contribute soon.

**Comment by Chalarangelo** [comment]
@sohelamin We will be performing most of the migration tasks today. I will see what is left over after we finish up (such as tests and packaging) and see what you might need to do then. No worries, though! Enjoy your vacation!

**Comment by Chalarangelo** [comment]
See #66
